food_class = {
    '麵類' : ['Bolonga Italian Restaurant','Hey Go Kopitian','Jenny Bistro 餐酒館','Le Bistro DOurs  小熊餐酒館 篤敬店 - 英法餐酒館 異國餐廳 推薦 人氣 宵夜 小酌聚會 創意經典調酒 創意料理 酒吧 打卡 生日慶生 特色餐酒 巨蛋商圈',
            'Jenny Bistro 餐酒館','Long De Beef Noodle Restaurant','Madker Live House & Restaurant','Mr. 帕（南洋料理、泰式酸辣麵、咖哩）','NOSE920 鼻子咖啡',
            'RÊVE 黑浮咖啡 高雄巨蛋店','WOO Taiwan 高雄旗艦店','Wubai Beef Noodle Restaurant','Youzhi Bing Tea','Yuanjing Xuan Restaurant',
            '一酒．點意','中都外省麵','京翠港式飲茶','伊凡的花園 coffee pizza pasta risotto','元町家 橫濱家系拉麵 高雄義享店','原味古早麵','國泰市場什菜麵',
            
            ],
    '美式料理' : ['Dandan Hamburg - but within shop','FOGGY Shisha & Bistro','Kaohsiung Kuaile Fried Chicken','NO Q pizza 西子灣','伊凡的花園 coffee pizza pasta risotto',
              '剛剛好_ _ - 手工漢堡 _ 高雄美味餐廳推薦 _ 高雄美食 _ _ _'] , 
    '炸物' : ['Dandan Hamburg - but within shop','FOGGY Shisha & Bistro','Jenny Bistro 餐酒館','Kaohsiung Kuaile Fried Chicken','Le Bistro DOurs  小熊餐酒館 篤敬店 - 英法餐酒館 異國餐廳 推薦 人氣 宵夜 小酌聚會 創意經典調酒 創意料理 酒吧 打卡 生日慶生 特色餐酒 巨蛋商圈',
            'Kaohsiung Kuaile Fried Chicken','Madker Live House & Restaurant','剛剛好_ _ - 手工漢堡 _ 高雄美味餐廳推薦 _ 高雄美食 _ _ _','天使雞排 瑞豐店',
            ],
    '飯食' : ['Bian Yi Fang','Bolonga Italian Restaurant','FOGGY Shisha & Bistro','Hey Go Kopitian','Jenny Bistro 餐酒館','Kaohsiung Kuaile Fried Chicken','Le Bistro DOurs  小熊餐酒館 篤敬店 - 英法餐酒館 異國餐廳 推薦 人氣 宵夜 小酌聚會 創意經典調酒 創意料理 酒吧 打卡 生日慶生 特色餐酒 巨蛋商圈',
            'LE GOÛT et LE GOÛT 樂穀餐酒館','Jenny Bistro 餐酒館','Long De Beef Noodle Restaurant','Madker Live House & Restaurant','Mr. 帕（南洋料理、泰式酸辣麵、咖哩）',
            'triple p. 三隻小豬','WOO Taiwan 高雄旗艦店','Youzhi Bing Tea','Yuanjing Xuan Restaurant','丹利手作料理','京翠港式飲茶','仲 鐵板燒 Teppanyaki Rest.',
            '伊凡的花園 coffee pizza pasta risotto','便宜坊烤鴨餐廳','內惟自助餐館','和美素食餐點','國泰市場（魯）肉燥飯，虱目魚粥','國泰海產粥',
            '地糖仔中式點心專門店','女爵莊園'] ,
    '西式' : ['Jenny Bistro 餐酒館','Le Bon Marche','LE GOÛT et LE GOÛT 樂穀餐酒館','Jenny Bistro 餐酒館','Mr.pa 帕先生','N I B B O N','Oui steak是牛排館',
            '一酒．點意','好市集 Le Bon Marche'] ,
    '日式' : ['Kaohsiung Kuaile Fried Chicken','Kaohsiung Kuaile Fried Chicken','Mr. 帕（南洋料理、泰式酸辣麵、咖哩）','Mr.pa 帕先生','triple p. 三隻小豬',
            '元町家 橫濱家系拉麵 高雄義享店','八田源 Japanese cuisine','八田源','初魚鮨','和食堂','品麵屋ラーメン雞白湯專賣','好湯日式涮涮鍋',
            ] ,
    '韓式' : ['I am Gogi 我是肉 韓式烤肉專賣店','八道晟韓式火烤吃到飽裕誠總店','北村豆腐家義享店'] ,
    '中式' : ['Apple Bear','Banana Pier','Bian Yi Fang','Day Day Food & Art','H2O HOTEL','Kaohsiung Kuaile Fried Chicken','Long De Beef Noodle Restaurant',
            'Old & New Taiwanese Cuisine','WOO Taiwan 高雄旗艦店','Wubai Beef Noodle Restaurant','Yuanjing Xuan Restaurant','中都外省麵',
            '丹利手作料理','京翠港式飲茶','仲鐵板燒 Teppanyaki Rest.','便宜坊烤鴨餐廳','內惟自助餐館','原味古早麵','合美素食','吳筒仔米糕','和美素食餐點',
            '國泰市場（魯）肉燥飯，虱目魚粥','國泰海產粥','地糖仔中式點心專門店','女子餃子','女爵莊園','好運餃'],
    '早餐' : ['Apple Bear','H2O HOTEL','Hong Fanjia Breakfast Restaurant','Nei Wei! Breakfast Restaurant','Yes Brunch','三兄弟蛋餅店','六合中式早點',
            '咕咕咕複合式早餐店'],
    '鍋物' : ['I am Gogi 我是肉 韓式烤肉專賣店','上官木桶鍋 高雄裕誠加盟店','井兵衛壽喜燒','八道晟韓式火烤吃到飽裕誠總店','北村豆腐家義享店','名家汕頭沙茶火鍋(瑞豐店)',
            '問鼎 皇上吉祥宮廷火鍋','大鍋頭 海鮮涮涮鍋&小鍋飯（美術青海店）','好湯日式涮涮鍋'],
    '烤肉' : ['Day Day Food & Art','Bullhorn Japanese BBQ (Tongmeng Branch)','I am Gogi 我是肉 韓式烤肉專賣店','和牛賀炭火燒肉'],
    '其他' : ['泰航泰式料理','German Soul Kaohsiung 德意所','Loracorlo 以色列料理餐廳','MAI 咖啡用餐','one泰平價泰式料理餐廳','Pasadena 美術','RYAN CAFE & MILK TEA',
            'SPR Coffee 神農旗艦店','Stain 漬','To Be Smoothie 綠果昔 美術館店','Woo 泰','Xingfu Shougong Dumpling Restaurant','不咖啡 BuCafe',
            '丸浜霜淇淋','亨寶咖啡','亨寶咖啡Humble Beginnings Cafe','內惟臭豆腐','再睡五分鐘 高雄義享店','冒煙的喬 高雄忠孝店','冬鄉小廚','力諾咖啡',
            '卡啡那CAFFAINA美術館店','卡茲咖啡','吳媽媽廣東粥','品好乳酪','國民市場魚丸料理 棧貳庫店','國立中山大學','大碗公冰品 西子灣店','天天新鮮果汁',
            '好乳酪蛋糕','好夥伴咖啡 巨蛋店']
}